name: SNU_SEES_10-10_project_seminar_LSM
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - numpy
  - xarray
  - scipy
  - pandas
  - matplotlib
  - cartopy
  - seaborn
  - sympy
  - ffmpeg
  - jupyter
  - netcdf4
  - nc-time-axis
  - jupyter-book=1.0.4.post1
  - tqdm
